// =============================================================
// Auto-generated by run_link.py — DO NOT EDIT
// Source: loader.s
// Verilog `initial` bloguna `include edilmek uzere uretilir.
// Header guard: bram.v `BRAM_INIT_LOAD`'i define eder.
// =============================================================

`ifdef BRAM_INIT_LOAD
    mem[ 0] = 32'h20000437;
    mem[ 1] = 32'h0d4000ef;
    mem[ 2] = 32'h0aa00293;
    mem[ 3] = 32'hfe551ce3;
    mem[ 4] = 32'h0c8000ef;
    mem[ 5] = 32'h05500293;
    mem[ 6] = 32'hfe5516e3;
    mem[ 7] = 32'h000104b7;
    mem[ 8] = 32'hfff48493;
    mem[ 9] = 32'h0b4000ef;
    mem[10] = 32'h00050913;
    mem[11] = 32'h0d8000ef;
    mem[12] = 32'h0a8000ef;
    mem[13] = 32'h00050993;
    mem[14] = 32'h0cc000ef;
    mem[15] = 32'h09c000ef;
    mem[16] = 32'h00050a13;
    mem[17] = 32'h0c0000ef;
    mem[18] = 32'h090000ef;
    mem[19] = 32'h00851293;
    mem[20] = 32'h005a6a33;
    mem[21] = 32'h0b0000ef;
    mem[22] = 32'h080000ef;
    mem[23] = 32'h01051293;
    mem[24] = 32'h005a6a33;
    mem[25] = 32'h0a0000ef;
    mem[26] = 32'h070000ef;
    mem[27] = 32'h01851293;
    mem[28] = 32'h005a6a33;
    mem[29] = 32'h090000ef;
    mem[30] = 32'h00000b13;
    mem[31] = 32'h000a0b93;
    mem[32] = 32'h013b0e63;
    mem[33] = 32'h054000ef;
    mem[34] = 32'h00ab8023;
    mem[35] = 32'h078000ef;
    mem[36] = 32'h001b8b93;
    mem[37] = 32'h001b0b13;
    mem[38] = 32'hfe9ff06f;
    mem[39] = 32'h03c000ef;
    mem[40] = 32'h00050a93;
    mem[41] = 32'h034000ef;
    mem[42] = 32'h00851293;
    mem[43] = 32'h005aeab3;
    mem[44] = 32'h01549c63;
    mem[45] = 32'h00200293;
    mem[46] = 32'h00590e63;
    mem[47] = 32'h00600513;
    mem[48] = 32'h030000ef;
    mem[49] = 32'hf41ff06f;
    mem[50] = 32'h01500513;
    mem[51] = 32'h024000ef;
    mem[52] = 32'hf35ff06f;
    mem[53] = 32'h000a0067;
    mem[54] = 32'h00442303;
    mem[55] = 32'h00137313;
    mem[56] = 32'hfe030ce3;
    mem[57] = 32'h00042503;
    mem[58] = 32'h0ff57513;
    mem[59] = 32'h00008067;
    mem[60] = 32'h00442303;
    mem[61] = 32'h00237313;
    mem[62] = 32'hfe031ce3;
    mem[63] = 32'h00a42023;
    mem[64] = 32'h00008067;
    mem[65] = 32'h00851293;
    mem[66] = 32'h0054c4b3;
    mem[67] = 32'h00010337;
    mem[68] = 32'hfff30313;
    mem[69] = 32'h0064f4b3;
    mem[70] = 32'h00800393;
    mem[71] = 32'h00008e37;
    mem[72] = 32'h01c4f2b3;
    mem[73] = 32'h00149493;
    mem[74] = 32'h00028863;
    mem[75] = 32'h00001e37;
    mem[76] = 32'h021e0e13;
    mem[77] = 32'h01c4c4b3;
    mem[78] = 32'h0064f4b3;
    mem[79] = 32'hfff38393;
    mem[80] = 32'hfc039ee3;
    mem[81] = 32'h00008067;
`endif // BRAM_INIT_LOAD
