// =============================================================
// Auto-generated by run_link.py — DO NOT EDIT
// Source: echo.s
// Verilog `initial` bloguna `include edilmek uzere uretilir.
// Header guard: bram.v `BRAM_INIT_LOAD`'i define eder.
// =============================================================

`ifdef BRAM_INIT_LOAD
    mem[ 0] = 32'h200002b7;
    mem[ 1] = 32'h0042a303;
    mem[ 2] = 32'h00137313;
    mem[ 3] = 32'hfe030ce3;
    mem[ 4] = 32'h0002a383;
    mem[ 5] = 32'h0ff3f393;
    mem[ 6] = 32'h0042ae03;
    mem[ 7] = 32'h002e7e13;
    mem[ 8] = 32'hfe0e1ce3;
    mem[ 9] = 32'h0072a023;
    mem[10] = 32'hfddff06f;
`endif // BRAM_INIT_LOAD
